name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - JacobBumgarner
body:
  - type: markdown
    attributes: 
      value: |
        Thanks for exploring VesselVio and taking the time to file a bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, please tell us how to replicate this bug.
      placeholder: Tell us what you see!
      value: "I found a bug!"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
  - type: dropdown
    id: app-build
    attributes:
      label: App Build
      description: How are you using VesselVio?
      options:
        - Manual app build (pyenv, conda, etc)
        - Downloaded App
    validations:
      required: true
  - type: textarea
    id: pseudocode-and-screenshots
    attributes:
      label: Pseudocode or Screenshots
      description: Feel free to include pseudocode or screenshots that led to the bug.
      placeholder: Provide some code for us to reproduce the bug!
      value: "```python \n
      Insert code here \n
      ```\n
      Or drag your screenshot here!
      "
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. 

