name: Feature Request
description: Request a feature to be added to VesselVio
title: "[Feature Request]: "
labels: ["feature-request", "enhancement"]
assignees:
  - JacobBumgarner
body: 
  - type: markdown
    attributes:
      value: |
          Thanks for taking the time to open this issue to help improve VesselVio!
  - type: textarea
    id: feature-details
    attributes:
      label: Describe the feature you would like to be added.
      description: |
        Provide a clear and concise description of what you would like added.
      placeholder: Tell us what you see!
      value: "I have a great idea for a new feature!"
    validations:
      required: true
  - type: textarea
    id: pseudocode-and-screenshots
    attributes:
      label: Pseudocode or Screenshots
      description: Feel free to include pseudocode or screenshots of the requested outcome
      placeholder: Provide some code for us to reproduce the bug!
      value: "```python \n
      Insert code here \n
      ```\n
      Or drag your screenshot here!
      "

